version: '3'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.4.30-debian-11-r37'
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'data:/bitnami/mariadb'
  moodle:
    image: 'docker.io/bitnami/moodle:4.1.4-debian-11-r22'
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DB_TYPE=mariadb
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - 'moodledata:/bitnami/moodle'
    depends_on:
      - mariadb
volumes:
  data:
  moodledata:
